### ISSUE TITLE
Player is not revealed on damage

### ISSUE THREAD

**Issue by a1exp** [Sphereserver/Source-X#791] opened 2021-10-25 23:17 UTC
On 56b when you are invisible and do damage to another character or self you are reveled. On SphereX not and didn't find proper REVEALF_* flag in .ini to turn it on. 

For instance when you are invisible and cast magic arrow to self you are not revealed. 

Can we add a new flag to init like REVEALF_DAMAGE ?

**Comment by drk84** [comment] 2021-10-31 10:07
I can't replicate it, i get properly revelead

**Comment by a1exp** [comment] 2021-10-31 18:06
@drk84 
That's interesting.. let's compare .ini flags? 

```
RacialFlags=0

// Reveal flags related to Invisible Spell
// REVEALF_DETECTINGHIDDEN		001		// Reveal Spell with Detecting Hidden Skill.
// REVEALF_LOOTINGSELF			002		// Reveal when looting self bodies (NOTE: Hidden characters will be always revealed by default).
// REVEALF_LOOTINGOTHERS		004		// Reveal when looting bodies of other Players or NPCs (NOTE: Hidden characters will be always revealed by default).
// REVEALF_SPEAK				008		// Reveal when speaking.
// REVEALF_SPELLCAST			010		// Reveal when starting to cast a Spell.
// REVEALF_OSILIKEPERSONALSPACE	0020	// Do not reveal hidden and invisible character when a character enters on personal space.
// REVEALF_SNOOPING				0040	// Do not reveal hidden players while snooping.
// REVEALF_STEALING				0080	// Do not reveal hidden players while stealing.
// REVEALF_STEALING_SUCCESS		0100	// Reveal hidden players when stealing successfully finished.
// REVEALF_STEALING_FAIL		0200	// Reveal hidden players when stealing failed.
// Set to 04 to make it behave like 55i.
RevealFlags=04 | 020 
```

```

// Extra magic flags to control magic/magery behaviour (default:0, 0.55i compatible)
// MAGICF_NODIRCHANGE           00001	// Not rotate player when casting/targeting
// MAGICF_PRECAST               00002	// Precasting (cast spell before target prompt)
// MAGICF_IGNOREAR              00004	// Magic damage ignore ar
// MAGICF_CANHARMSELF           00008	// Magic can do damage on self
// MAGICF_STACKSTATS            00010	// Different stat spells don't cancel each other out
// MAGICF_FREEZEONCAST          00020	// No movement whilst casting
// MAGICF_SUMMONWALKCHECK       00040	// Summoned creatures should be able to walk on the target location (e.g. water creatures to be summoned on water)
// MAGICF_NOFIELDSOVERWALLS     00080	// Field spells cannot cross over blocking objects
// MAGICF_NOANIM                00100	// Auto SPELLFLAG_NO_ANIM in every spell
// MAGICF_OSIFORMULAS           00200	// Calculate spell damage and duration based on OSI formulas
// MAGICF_NOCASTFROZENHANDS     00400	// Can't cast spells if got paralyzed holding something on hands
// MAGICF_POLYMORPHSTATS	00800	// Polymorph spells give out stats based on base chars (old behaviour backwards)
// MAGICF_OVERRIDEFIELDS        01000	// Prevent cast multiple field spells on the same tile, making the new field tile remove the previous field
// MAGICF_CASTPARALYZED		02000	// Can cast even if paralyzed
// MAGICF_NOREFLECTOWN		04000	// Do not reflect own spell if the spell has already reflected from the target.
// MAGICF_DELREFLECTOWN		08000	// Remove reflection instead of damage himself when NOREFLECTOWN active if the spell reflected from another target.
MagicFlags=0200d
```

**Comment by drk84** [comment] 2021-10-31 18:29
RevealFlags=01|02|04|08||040|080|0200

MagicFlags=08

**Comment by a1exp** [comment] 2021-11-01 14:00
@drk84 
hm.. are you using the latest build with this [issue ](https://github.com/Sphereserver/Source-X/issues/776) fixed? OTherwise reveal can be done due to `REVEALF_SPEAK`.

Also, please take a look at this code, this is obvious that reveal is not performed when damage self (`if (pCharSrc == this)`):

https://github.com/Sphereserver/Source-X/blob/f24687c5330f8fbf7b7ae9f626447fc91e280d77/src/game/chars/CCharFight.cpp#L315-L327

**Comment by drk84** [comment] 2021-11-01 16:24
I found the issue,  my reveal is caused by // FEATURE_AOS_DAMAGE           08 // Show damage values above char head when deal/receive any damage

**Comment by drk84** [comment] 2021-11-03 09:48
My fault i had an event sending using say somewhere

**Comment by drk84** [comment] 2021-11-03 09:51
Additionally, it seems by default Sphere adds to all damaging spells the dam_noreveal flag. 
So it's not a bug.

**Comment by drk84** [comment] 2021-11-15 08:16
I close this

**Closed by drk84** 2021-11-15 08:16 UTC
Labels: Type: Invalid issue
