### ISSUE TITLE
magic reflection

### ISSUE THREAD

**Issue by alexrmrm** [Sphereserver/Source-X#458] opened 2020-05-04 07:02 UTC
If player cast to times magic reflection byself, with second magic reflection remove effect.

On other spells that not success, for example wih bless u cast sometimes spell and not removed effect.

I don't know if he's in core for something. I only put it for evaluation, by script you could make it not happen too.

**Comment by GitMadKing** [comment] 2020-05-04 07:17
i think is nasty to get a decision.
magic reflection
reflect MAGIC
so it's normal.
but also should reflect heal, cure, bless.. etc
so i think best practice is to NOT reflect spellflag_good

**Comment by xwerswoodx** [comment] 2020-05-04 11:26
Reflection doesn't reflect good spells at all, only the spells that has spellflag_harm flag reflecting. I checked the code XuN changed yesterday about spells but seems like nothing changed about that. Maybe I can make a test a little.

**Comment by alexrmrm** [comment] 2020-05-04 15:08
sorry my english, i mean when you cast magicreflection twice yourself

**Comment by GitMadKing** [comment] 2020-05-06 09:11
check you spell to not have spellflag_harm
cannot reproduce, here timer restart (override itself)
```
[SPELL 36]
// NOTE: This is a proactive type of protection that no one wants to see run out. Because of it's level and the amount of reagents I would think this spell last a bit longer in light of it only being a one time reflect as opposed to Reactive and protection. Should it have a duration at all or remain until dispel'ed or hit ???
DEFNAME=s_magic_reflection
NAME=Magic Reflection
SOUND=snd_spell_magic_reflection
RUNES=IJS
CAST_TIME=1.5
RESOURCES=i_reag_garlic,i_reag_mandrake_root,i_reag_spider_silk
RUNE_ITEM=i_rune_magic_reflection
SCROLL_ITEM=i_scroll_magic_reflection
FLAGS=spellflag_dir_anim|spellflag_targ_char|spellflag_fx_targ|spellflag_good|spellflag_playeronly|spellflag_bless
EFFECT_ID=i_fx_bless_effect
EFFECT=0
LAYER=layer_spell_magic_reflect
DURATION=4*60.0,8*60.0
MANAUSE=14
SKILLREQ=MAGERY 50.0
INTERRUPT=100.0,100.0
```

**Comment by xwerswoodx** [comment] 2020-12-21 02:25
I checked it with latest version but seems like it is working fine, please check if the issue still happening and try to explain which path you follow so we can test it. But as I said before Magic Reflection is reflect spellflag_harm flagged spells, so please check your Magic Reflection flags also.

**Comment by Tolokio** [comment] 2022-12-09 23:36
@alexrmrm resuelto el issue? podemos cerrar?

**Comment by drk84** [comment] 2023-01-02 13:14
I close this anyway

**Closed by drk84** 2023-01-02 13:14 UTC
Labels: Status: More info needed, Status-Bug: To be confirmed
