### ISSUE TITLE
Dropping intos into wall tiles in multis

### ISSUE THREAD

**Issue by Soulless-1** [Sphereserver/Source-X#1024] opened 2023-02-08 16:19 UTC
You can drop items onto tiles that you would regularly not be able to do so on, such as into a wall. 

![image](https://user-images.githubusercontent.com/17236327/217588126-a057ef5f-17ea-48dd-94ae-a15698d4dda2.png)

**Comment by Jhobean** [comment] 2023-02-10 18:21
Same: https://github.com/Sphereserver/Source-X/issues/704

**Comment by AtillaG1** [comment] 2023-02-11 17:27
As a player i remember this was always a thing with older spheres.
This way people that didnt know, they locked their containers wrongly and got robbed until they realised.

I think the problem is that the floor is shared with the wall and this way its correctly on the floor, but the wall isnt taken in as problem.
With normal static walls it should not be possible to achieve,

**Comment by Soulless-1** [comment] 2023-02-11 20:12
I don't recall being able to do that, and i would say even in the event that it was possible, that it is a bug and should be fixed, since it is not normal UO mechanics.

**Comment by drk84** [comment] 2023-02-19 21:17
Fix sent

**Comment by drk84** [comment] 2023-04-06 12:26
I close this

**Closed by drk84** 2023-04-06 12:26 UTC
Labels: Status-Bug: Confirmed, Status: Done - waiting feedback
