### ISSUE TITLE
Remove internal message for fail mining spots

### ISSUE THREAD

**Issue by ted182** [Sphereserver/Source-X#1264] opened 2024-07-09 23:53 UTC
When we are mining and fail to withdraw ore, we receive 2 messages:

```
There is no ore here to mine.
You loosen some rocks but fail to find any useable ore.
```

the first sentence comes internal (hardcoded) and the second comes from the file skill45_mining.scp (@fail trigger)
I believe that it doesn't make much sense to receive the 2 sentences and the sentence that comes hardcoded is confusing if the prayer is over, I think that only the second sentence would be enough 

I would like to suggest that a comment be placed in the server file:
\src\game\chars\CCharSkill.cpp

the code is:
```
CItem *pItem = Skill_NaturalResource_Create(pResBit, SKILL_MINING);
if ( !pItem )
{
	SysMessageDefault(DEFMSG_MINING_3);
	return -SKTRIG_FAIL;
}
```

remove this DEFMSG_MINING_3 would be enough
what do you think? it makes sense?

**Comment by Soulless-1** [comment] 2024-07-10 04:08
one indicates that there is no ore on the node, the other indicates a failure. it's two separate messages.

**Comment by ted182** [comment] 2024-07-10 10:43
and do you need 2 sentences? I think just indicating the failure is enough. The one coming from the internal server is confusing.

**Comment by Soulless-1** [comment] 2024-07-10 10:49
considering that they are two completely separate types of scenarios yes i believe two sentences would be required.

**Comment by ted182** [comment] 2024-07-10 11:18
when there is no ore there is already a very clear sentence (internal server var DEFMSG_MINING_2):
`There is nothing here to mine for.`
I think it's confusing when the phrase appears:
`There is no ore here to mine.`

For me, the 2 sentences above say the same thing, but appearing in different situations.

**Comment by Soulless-1** [comment] 2024-07-10 11:27
const CRegion *pArea = GetRegion();
    if (pArea->IsFlag(REGION_FLAG_NOMINING))
    {
        SysMessageDefault(DEFMSG_MINING_2);
        return -SKTRIG_QTY;
    }
    
    one of those indicates that the region is not an area you can mine in, with the flag region_flag_nomining. a more clear version that indicates nothing would be there for you to mine for in any instance it would seem. noting that these situations are different i see no issue with the messages having nuances that inform the player of this.

**Comment by ted182** [comment] 2024-07-10 12:07
I agree that you are right in the code snippet you showed, but it also appears in this situation:
```
if ( pResBit->GetAmount() == 0 )
{
 SysMessageDefault(DEFMSG_MINING_2);
 return -SKTRIG_QTY;
}
```
and here it would not be a non-minable area, but rather indicating that you have zeroed the mining spot. This message appears in mineable zones after you have mined all the respawn

**Comment by Tolokio** [comment] 2024-07-10 20:42
hmm Have been testing it a little. System works fine for me.

I think 2 messages can appear only in rare circunstances (not tested)
For example, if someone empty a spot where u was already mining. That or u have a script that remove amount on spot when u fail.

**Comment by Soulless-1** [comment] 2024-07-11 10:19
Ah I believe i must of misunderstood you Ted, you are receiving both messages at once during failure? I agree completely that is confusing to the player 👍 I will try to recreate on a fresh sphere X

**Comment by ted182** [comment] 2024-07-11 10:47
Sorry for the delay friends, time is a little busy here. The 2 messages always appear when there is a failure to capture the ore. You can try to download the fresh server and put it to mine and whenever it fails, the 2 appear.

**Comment by Tolokio** [comment] 2024-07-14 19:16
> Sorry for the delay friends, time is a little busy here. The 2 messages always appear when there is a failure to capture the ore. You can try to download the fresh server and put it to mine and whenever it fails, the 2 appear.

Tested on fresh build. I just get one message when I fail by low skill.

Another thing that could b happeningto you is that the mining_spawn is being created empty. (amount 0) I know this were happening years ago, but can't remember why. MAybe regions got something to do there but I dont know.

Check if ur spawn are being created empty using this way:
-First activate: .gm .debug .resend
-Once you see there is no spawn created in the spot u are going to mine.
-Do again .gm .debug.resend
-Then mine as a normal player just once. If u receive the 2 messages then:
-Do .gm .debug .resend and check the "amount" of the spawn.

If that is not the reason, maybe ur script or sphere is using morex morey more1 or whatever instead amount and always thing it is empty even if amount is 25 

By my part, I have not been able to reproduce it.

**Comment by ted182** [comment] 2024-07-14 23:21
I'm not even able to reproduce this error, after restarting the server apparently this stopped happening, but I'm still trying to check. As soon as I can reproduce it in a more concrete way, I will comment again here.

**Comment by Soulless-1** [comment] 2024-07-15 16:34
i did try this myself on a fresh shard also just now and cannot recreate either. let us know what you find when trying again. thanks!

**Comment by Tolokio** [comment] 2024-08-29 15:56
Lets close this red182? As u  created the issue u can close. Plz do it. U can reopen it later if it happen again.

**Closed** 2024-08-29 16:51 UTC
