### ISSUE TITLE
Trigger @DESTROY and Packet Send

### ISSUE THREAD

**Issue by alexdan2** [Sphereserver/Source-X#415] opened 2020-04-17 21:51 UTC
I Make some test, when weapon go to HITS 0 server call event @DESTROY, this happen for all item bow, weapon ecc.

But when use a dagger and HITS go to 0 see emote weapon destroy and server send remove item packet. For now all regular. When use a bow (or two hand weapon), trigger @DESTROY fire, see emote, but server not send remove item packet.

How reproduce - WORK:
- Add bow (.add i_dagger)
- Set hits to bow to 0 (.set hits 0 -> Target Bow)
- Make 2/3 hits to a mobs 
- See emote item destroy (and client recevied remove item packet, WORK GOOD!)

How reproduce - BUG:
- Add bow (.add i_bow)
- Set hits to bow to 0 (.set hits 0 -> Target Bow)
- Make 2/3 hits to a mobs 
- See emote item destroy (but client not recevied remove item packet, BUG!)

Additional Info:
- Tested on last release 3268

**Comment by JulianUO** [comment] 2020-04-19 22:09
This might be a duplicate of #412

**Comment by alexdan2** [comment] 2020-04-19 22:38
@JulianUO Hmmm not sure is a duplicate of #412 because 100% of time work for dagger and 0% work for i_bow, But possible.. when #412 is fixed i retest this problem

**Comment by GitMadKing** [comment] 2020-04-20 20:14
maybe is just not removed from view?
try to put under the bow
```
ON=@DESTROY
removefromview
```

**Comment by alexdan2** [comment] 2020-04-20 21:20
@GitMadKing I try your code, but nothing happen. i add a serv.log on @destroy, and server call trigger but removefromview not work, i also try update ecc but nothing. 
If i logout and login yes work, because get fresh data.

**Comment by GitMadKing** [comment] 2020-04-20 21:44
in this case i'm almost sure is not related to #412 
i'll do some test tomorrow.
what client version do you use?

**Comment by alexdan2** [comment] 2020-04-20 21:47
Tested whit 7.0.20.0 also tested on ClassicUO.. same issue

**Comment by JulianUO** [comment] 2020-04-20 23:16
Okay, so, I just tested a few times, with an halberd, pitchfork, bow.
Everytime my weapon gets removed from server, it gets removed from view also.
Can't reproduce it.

Can you do a big search for your scripts and look for a @Destroy trigger on items?

**Comment by alexdan2** [comment] 2020-04-21 01:20
I found the mistery is problem on @UnEquip, if i use a update here for some reasons not correct execute @destroy. 

```
[TYPEDEF t_weapon_bow]

ON=@UnEquip
	SRC.f_testfunction	//per essere certi che non rimanga flag di sparo in movimento
```

```[FUNCTION f_testfunction]
--- Some operation--
I.UPDATE --> This is the cause of item not correct refresh
RETURN 1
```

Is possible is my logical error because i fire a update when unequip and go in conflict whit @destroy because this fire also a unequip

**Comment by JulianUO** [comment] 2020-04-21 14:04
Unequip must be fired to remove all item properties from the char, like armor.
I suggest checking for hits in your function before any update function.

**Closed** 2020-04-24 00:32 UTC
