### ISSUE TITLE
Sphere internal functions return "Can't resolve" instead of 0 when not valid 

### ISSUE THREAD

**Issue by Rizzzolo** [Sphereserver/Source-X#797] opened 2021-10-31 03:18 UTC
Hi all, 

I have noticed that all sphere internal functions return "Can't resolve" instead of 0 when not satisfied. 

As very stupid example: 
serv.b <findlayer.1.name> will return "Can't resolve" instead of 0.

To avoid the error pops-up, I need extra code like:

If <findlayer.1.isvalid>
Serv.b <findlayer.1.name>
Endif

On previous 56c/d, there was no need to check "isvalid" since the internal function was automatically returning 0 when not valid.

**Comment by Rizzzolo** [comment] 2021-10-31 03:22
Forgot to mention: this applies to all sphere internal functions.

**Comment by Jhobean** [comment] 2021-10-31 03:53
Its not a bug it's intended to be like this. It's a check make by the server. There a isvalid check you must do in script

**Comment by Jhobean** [comment] 2021-10-31 05:14
Yes it could cause lot of headhache when you merge old script on X but trust me, you'll not regret the adjusment. With This new warning you find lot of weird bug hard to find.

**Comment by drk84** [comment] 2021-10-31 10:03
I close this

**Closed by drk84** 2021-10-31 10:03 UTC
Labels: Type: Invalid issue
