### ISSUE TITLE
Dragon Breath with no delay

### ISSUE THREAD

**Issue by RodVIII** [Sphereserver/Source-X#689] opened 2021-05-24 21:06 UTC
I found odd they were using the breath action 4-5 times in less than a second on my server. So I downloaded a clean scriptpack and the latest X version to test it. It still happens.

To reproduce: just create a greater dragon (or whatever dragon), wait for him to use the breath action on you. Sometimes he will breath 3-4 times in less than a second.

**Comment by drk84** [comment] 2021-05-25 07:57
I can't reproduce it

**Comment by drk84** [comment] 2021-06-07 20:12
Found the issue

**Comment by drk84** [comment] 2021-06-07 21:15
Fix Sent.

**Comment by drk84** [comment] 2021-06-22 16:42
I close this, it seems fixed to me.

**Closed by drk84** 2021-06-22 16:42 UTC
Labels: Status-Bug: Confirmed, Status: Done - waiting feedback
