### ISSUE TITLE
Hiding and NPC Going Home

### ISSUE THREAD

**Issue by Swiftik023** [Sphereserver/Source-X#343] opened 2019-11-20 22:20 UTC
I have a problem with hiding and NPC.
When I will hide in front of NPC they revealed me when 'Going Home'. 
I see npc, npc see me --> npc attacking me *you see xxx is attacking you*, *you see xxx Wrestling* --> I will hide --> *you see xxx Going Home* and 'You have been revealed'

It's not good...

try on Compiled at Nov  3 2019 (18:48:12) [build 3183 / GIT hash 4f2007b028d24fa0bca83e4c0726098347b5b79e]
scripts: own & nolok

**Comment by Seokotov** [comment] 2019-11-20 22:52
my players told me about problems with hiding, it's not npc detecting, just hiding seems like bugged

**Comment by Swiftik023** [comment] 2019-11-23 18:17
without npc I have no problem with reveal

**Comment by Seokotov** [comment] 2019-11-24 15:38
my players often reported about detecting by npc in dungeons
even if npc have no detecting hidden skill in their scripts

**Comment by Swiftik023** [comment] 2019-11-26 22:41
https://www.youtube.com/watch?v=2k_O7SzgLks&feature=youtu.be

**Comment by Seokotov** [comment] 2019-12-12 17:40
if player under attack he can't hide from npc
if go hide you will be detected
npcs have no detecting skill

**Comment by fjgo86** [comment] 2019-12-17 18:38
Can this be reproduced with latest build and scripts, both default? I can't seem to reproduce it so if you can, please provide the steps to reproduce it.

**Comment by Swiftik023** [comment] 2020-02-02 13:40
> Can this be reproduced with latest build and scripts, both default? I can't seem to reproduce it so if you can, please provide the steps to reproduce it.

same problem: https://www.youtube.com/watch?v=2k_O7SzgLks&feature=youtu.be
spawn morep: 30,35,5
npc flags: 010004000

**Comment by xwerswoodx** [comment] 2020-03-31 23:18
I checked it with the latest build and there is no problem on hiding skill, can you check if the issue still occurs? If not, you can close the issue.

**Comment by Swiftik023** [comment] 2020-04-09 22:53
the problem is still active

**Comment by xwerswoodx** [comment] 2020-04-09 22:56
Do you have any script? Maybe your scripts causes that? Because I am hiding, walking, running near npcs without having any issue,

**Comment by xwerswoodx** [comment] 2020-04-09 23:04
Oh okay, seems like only gms has this issue, if you are a player, you can still hidden, but if you are a gm, you quickly unhidden.

**Comment by Swiftik023** [comment] 2020-04-10 12:29
I try it on myself script and nolok script on latest sphere

when I am hiding, walking, running near npcs it's ok problem is when NPC attack me.

- NPC is attacking you 
- you use hidding
- NPC going home
- you are revealed

from video (https://www.youtube.com/watch?v=2k_O7SzgLks&feature=youtu.be)
NPC attack: "*Vidis jak Wraith na tebe utoci!*" "*Vidis jak Wraith use wrestling*"
I use hidding
NPC loose target: "*Vidis jak Wraith Going Home*"
and I am revealed

**Comment by xwerswoodx** [comment] 2020-05-03 00:15
Could you check if the issue still going on? Because it seems like I have no issue about that at all.

**Comment by Jhobean** [comment] 2020-09-21 03:38
Maybe link to this issue: https://github.com/Sphereserver/Source-X/issues/485  Monster seem stop attacking too.

**Comment by Massi17** [comment] 2020-12-03 21:42
with // NPC_AI_PATH  00001	Enable advanced NPC pathfinding engine (this can significantly increase server CPU usage) enabled, 
-mob is attacking you
-you use hiding skill
-when the monster gives you his back you will be revealed

**Comment by xwerswoodx** [comment] 2020-12-20 19:55
[https://www.youtube.com/watch?v=Rg6dBA5fQ3M&feature=youtu.be&ab_channel=HamitDevecio%C4%9Flu](url)
Here is what happened for me at all. I have never revealed if it doesn't move in my personal space. NPCAI is 01 so NPC_AI_PATH also activated (I tried both disabling npcai at all and enabling all of them) but the result is totally same.

If you still have same issue please share your;
skills script file (sphere_skills.scp in default)
any necessary scripts (like functions under hiding skill etc.)
sphere.ini file (don't forget to remove mysql passwords and your ips inside of it)
event scripts (if you have any player events, npc events, or any other events to affect player or npcs)
or;
just share your sphere pack through me from discord xwerswoodx#4332. So I can test it on your sphere to see what causes the issue.

**Comment by xwerswoodx** [comment] 2020-12-20 20:31
Anyway, i confirmed bug with some test done with @Mirror, I will return and make fix if I found out the reason what causes revaling.

**Comment by xwerswoodx** [comment] 2020-12-20 22:10
I found out what causes this issue;

This is halfly issue and halfly not, so I am leaving a note here until find any solution for this.
```File: CCharAct.cpp
Caused In: CRegion * CChar::CanMoveWalkTo( CPointMap & ptDst, bool fCheckChars, bool fCheckOnly, DIR_TYPE dir, bool fPathFinding )
Statement Cause Issue:
			else if ( pChar->IsStatFlag(STATF_HIDDEN) )
			{
                snprintf(pszMsg, STR_TEMPLENGTH, g_Cfg.GetDefaultMsg(DEFMSG_HIDING_STUMBLE), pChar->GetName());
                pChar->Reveal(STATF_INVISIBLE | STATF_HIDDEN);
			}
Reason:
Npc checking path to walk, but the system blocks npcs to move on player but when it already tried to move side of player, it reveals hidden because Sphere see personal space intention. We have personal space reveal flag for invisibility but for hidden, if we cancel this npcs never reveal hidden players when moved on, so we need to find some solution for it (maybe trigger after npc moved on player? or something like this.)```

**Comment by Jhobean** [comment] 2021-07-20 01:38
@xwerswoodx  the reason you explain is interesting. If I understand well, NPC is not on the same position of the player and it reveal anyway? It,s reveal because Sphere "simulate" the path on the player?

If yes, what about making a check of the NPC position and Player position? If position is equal you reveal. Else, you pass.

**Comment by drk84** [comment] 2022-06-30 08:58
I close this

**Closed by drk84** 2022-06-30 08:58 UTC
Labels: Status: Help wanted, Status: Done - waiting feedback, Priority: Medium, Status-Bug: To be confirmed
