### ISSUE TITLE
summoned creature (mounted)

### ISSUE THREAD

**Issue by Soulless-1** [Sphereserver/Source-X#712] opened 2021-06-19 12:36 UTC
When you summon a creature and mount it, once you are on it they wont unsummon till you get off of it.  so you can ride it forever until you dismount, then it will be unsummoned immediately

**Comment by Jhobean** [comment] 2021-06-19 18:00
Dupe of #582

**Comment by drk84** [comment] 2021-06-22 16:32
I close this one!!

**Closed by drk84** 2021-06-22 16:32 UTC
