### ISSUE TITLE
@ItemBuy act is incorrect

### ISSUE THREAD

**Issue by slow-loki** [Sphereserver/Source-X#763] opened 2021-09-15 08:44 UTC
When using the @ItemBuy trigger act is documented as the item the player will receive however act is the item(s) stored on the NPC.

If you do the following the item on the NPC is deleted. 

[EVENT fortheplayer]
ON=@ItemBuy
  act.remove
  
![itemselltrigger](https://user-images.githubusercontent.com/73989785/133401236-7e574a45-8839-44ca-8957-f5c089348cd4.gif)

**Comment by drk84** [comment] 2021-09-16 14:34
Can't reproduce, the item is properly removed from the vendor list

**Comment by drk84** [comment] 2021-09-16 14:35
In your player event  in the @Itembuy trigger use this
serv.log <name> buying <act.name> from <argo.name>

**Comment by Jhobean** [comment] 2021-09-16 15:55
@drk84 yep.. and what it should do is delete in the player bag not the vendor one

**Comment by xwerswoodx** [comment] 2021-11-01 16:25
Basically ACT is equals to the item on the vendor, not the item on the player's backpack. Because ItemBuy called before buying the item, so the new item haven't been created yet, so there is no way to get new item under @ItemBuy trigger. Also even we add new trigger that called after player bought and item, there could be issues also, for example, some items like armors, not stackable, so what happens if you buy 10 platemail gauntlets? Which one gonna be ACT? Can be saved as a list, or list of locals but is it really worth to do it? Because if you want to remove the items they bought you can just start 1 sec timerf and check player backpack for <act.baseid> and consume <act.amount> <act.baseid> from player.

**Comment by drk84** [comment] 2022-06-30 08:30
I close this

**Closed by drk84** 2022-06-30 08:30 UTC
Labels: Status: More info needed
