### ISSUE TITLE
Spell casting interrupts melee attack

### ISSUE THREAD

**Issue by wagneruo** [Sphereserver/Source-X#1010] opened 2023-01-13 23:49 UTC
Spell casting interrupts melee attack
When you hit another player or NPC and cast spell you just stopping to hit them. 

In old old spheres it was fine

Tested in fresh latest build

**Comment by Jhobean** [comment] 2023-01-14 01:20
You mean you are able to hit someone during casting?:flushed:

Example you cast flame strike, during the 10 sec of wait you can hit someone?

**Comment by wagneruo** [comment] 2023-01-14 08:01
> You mean you are able to hit someone during casting?😳
> 
> Example you cast flame strike, during the 10 sec of wait you can hit someone?

no, you just stop hit after casting, need to push attacklast. it looks like you loose target

**Comment by Tolokio** [comment] 2023-08-18 13:39
confirmed, dont know if it is a bug but happen to me as well.

**Comment by cbnolok** [comment] 2023-09-21 12:17
I remember it happening this way in 56b. Since casting is a different skill, to keep that old behavior (even precedent to 56b?) sphere would have to change skill to magery and at the end switch back to the previous one (the last part would now be done manually via attacklast). Honestly, i wouldn't change that

**Comment by wagneruo** [comment] 2023-10-10 00:42
> I remember it happening this way in 56b. Since casting is a different skill, to keep that old behavior (even precedent to 56b?) sphere would have to change skill to magery and at the end switch back to the previous one (the last part would now be done manually via attacklast). Honestly, i wouldn't change that

just need to fix target loosing for hitting...because of the cast spell, the player loses the target and stops hitting

**Comment by Soulless-1** [comment] 2024-09-10 16:57
This can be added on player events, or even all char event

`on=@spellfail
if (<flags>&statf_war)	//doesn't go back into attacking with melee 
  timerf 0,action <qval (<weapon.isvalid>)?<weapon.skill>:wrestling>
endif

on=@spellsuccess
if (<flags>&statf_war)	//doesn't go back into attacking with melee 
  timerf 0,action <qval (<weapon.isvalid>)?<weapon.skill>:wrestling>
endif`

**Comment by Soulless-1** [comment] 2024-09-12 08:51
closing out, please comment if the issues persists, i recommend using the code above, as we can keep this functionality and its easily prevented

**Closed by Soulless-1** 2024-09-12 08:51 UTC
Labels: Status: Planned/Accepted, Priority: Low, Type: Feature request (change)
